version: '3.8'

services:
  playpointplaylist:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: playpointplaylist
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/playlist.db
      - YouTubeApi__ApiKey=${YOUTUBE_API_KEY}
      - AdminSettings__Password=${ADMIN_PASSWORD}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - playlist-network

networks:
  playlist-network:
    driver: bridge
